name: unity-build
on: [push, pull_request]
jobs:
  build_win:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Unity Editor
        uses: game-ci/unity-setup@v4
        with:
          unityVersion: '2022.3.0f1'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Activate Unity
        uses: game-ci/unity-activate@v2
        with:
          unityLicense: ${{ secrets.UNITY_LICENSE }}
      - name: Build (Windows x86_64)
        uses: game-ci/unity-builder@v4
        with:
          projectPath: UnityGame
          targetPlatform: StandaloneWindows64
          buildName: Game-Win64
          buildsPath: Build
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Game-Win64
          path: Build/StandaloneWindows64
